### ISSUE TITLE
Sky Resources Cauldron Cleaning breaks with Inspirations Cauldron

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [KnightMiner/Inspirations#122]
Hi there,

so, I recently tried using Inspirations' Cauldron Module with Sky Resources' Rock Cleaning feature and there unfortunately seems to be a glitch with the interaction between the two:

When cleaning dirty gems with Sky Resources in a Vanilla cauldron, the cauldron has a set % chance to empty by one unit (which was, I think, a quarter of a cauldron each time?). You'd only be able to clean rocks until the cauldron's tank was empty, and then you just had to refill it.

Now, this seems to work with a *Vanilla* cauldron, but when using Inspirations cauldrons, the story changes - I'm still only able to clear rocks until a certain point, but the Cauldron stays full. At some point, the cauldron can't be used to clean rocks anymore, but I'm *still* able to retrieve a full bucket. Now, I'm assuming this is because of the way Sky Resources does things with cauldrons rather than Inspirations, but I still felt like reporting this to you first, maybe you're able to figure out what's going on?

**Comment by KnightMiner** [comment]
This is on SkyResources side, and looking through their code its about 10 times worse than I expected.

Apparently, instead of casting `Blocks.CAULDRON` to `BlockCauldron` before calling `setWaterLevel`, they [create a new instance of `BlockCauldron` on every right click](https://github.com/Bartz24/SkyResources/blob/1.12-2.0/src/main/java/com/bartz24/skyresources/events/EventHandler.java#L107), which is not only wasteful, but prevents compatibility. If they just switch that to calling it from `Blocks.CAULDRON` it will fix this bug.

**Comment by MaxNeedsSnacks** [comment]
The issue has been fixed on the SR side, thanks a bunch for helping out with identifying the cause ^^
