### ISSUE TITLE
[Suggestions] About key and lock

### ISSUE THREAD

**Issue by Snownee** [KnightMiner/Inspirations#13]
* Crafting a named key / lock with a blank key / lock to copy this item
* Placing lock on anvil, wooden door, etc, to forbid others to use this block

**Comment by KnightMiner** [comment]
Locked doors is on my to-do list since I need to special case them. I see no point locking anvils or most other vanilla blcoks. For any blocks from mods they just need to implement the relevant vanilla interface 

Probably will not do key/lock copying by crafting, I like that it takes XP to craft them and it makes it feel more like locksmithing. Note you can name multiple keys at once.

**Comment by Snownee** [comment]
Because you really "consume" the anvil when using it :)

**Comment by KnightMiner** [comment]
Eh, it's more effort to support anvils then it is worth. Besides, if i place a little lock on am anvil, is that really going to stop someone from using it? It's a giant hunk of metal.

**Comment by Snownee** [comment]
OK it makes sense
