### ISSUE TITLE
support for foresty, pam's harvestcraft, natura drinks, soups, stews

### ISSUE THREAD

**Issue by Hypsellis** [KnightMiner/Inspirations#130]
It would be really nice to enable the forestry, pam's harvestcraft, natura drinks, soups, stews to be performed in the cauldron. I can make a list of all the drinks if you plan to support them.

I didn't understand the use of the condensed items for making soups and stews. Drinks and potions could be performed by putting ingredients ones by ones.

**Comment by KnightMiner** [comment]
This is something I would consider, would you mind giving a more full list from each mod?

The reason for the condensed items is because I want to keep cauldron's behavior vanilla. I dont want cauldrons to hold a temporary list of items until the user puts the rest in as that leaves it in an invalid state for other recipes, I instead decided every time you use an item on the cauldron it must change the fluid inside. This means to support items one by one, I would need to have a fluid for each partial state. That is not terrible for mushroom stew, but for rabbit stew that is a ton of combinations. I may look into it again for the 1.14 update as I plan to rework cauldrons, but I have no plans to change it in the 1.12 version

**Comment by 0Navis0** [comment]
I'm sorry to have not answered to you post before, I had forgotten it. It makes some monthes I abandoned to 1.12 and moved to 1.14, and I think most of modders and players did the same. It would be better to wait for Inspirations, Pam Harvestcraft, and Forestry to update to 1.14, and see how it turns, it will save a lot of useless work.

**Comment by Echoweaver** [comment]
I've been looking at doing Harvestcraft soups with CraftTweaker. It would be nice to have a broth liquid, since most Harvestcraft soups create that as an intermediate item. Several of the soups are cream soups, and I assume those would start with milk instead of water (that sounds kind of cool to me actually).

I'm happy to provide you with the recipes if you're at all interested in pursing this.

**Comment by KnightMiner** [comment]
I am done with 1.12 development at this time. You can easily add this yourself using a mod such as ContentTweaker to add a custom fluid.
