### ISSUE TITLE
Glowing Fluids don't glow in cauldrons

### ISSUE THREAD

**Issue by zauberparacelsus** [KnightMiner/Inspirations#136]
When a light-emitting fluid such as lava is placed in a cauldron, no light is produced by the fluid.  As well, the texture has no emission, and so will be darkened like any other block in dim light.

**Comment by KnightMiner** [comment]
I am not sure if there is anything I can do about this, but I can look into it. One big detail is cauldrons are a block model rather than a tile entity, so I cannot make the fluid texture "glow" properly. I can look into making it emit light though as I am already triggering block updates when you change the fluid.

**Comment by KnightMiner** [comment]
I just tested this and it appears the game does not like me having the light level based on the TE, despite sending block updates. I will have to look into this more at a later date but for now this is "can't fix"

**Comment by KnightMiner** [comment]
Closing this as not planned for 1.16. 1.18 made each fluid its own block thus making them glow is trivial.
