### ISSUE TITLE
Support for Chisel Carpets

### ISSUE THREAD

**Issue by zauberparacelsus** [KnightMiner/Inspirations#140]
The carpet adds some new carpets, which have ornate patterns instead of a solid color.  Would it be possible to extend support to them so that they can go on stairs and trapdoors?

**Comment by KnightMiner** [comment]
No, this is not something I plan to do.

* For stairs, it requires me replacing the vanilla carpets with my own blocks, this is fine for vanilla blocks but very bad practice to do for another mod. If you want this feature you are best off asking on the Chisel GitHub.
* For trapdoors, every single variant of carpet is it's own block, which is part of the reason I only have a generic wood texture instead of each wood type. I would have to register an additional block for every different chisel carpet type, which is not something I intend to do. This is a feature that might fit in Unlimited Chisel Works.
