### ISSUE TITLE
Can't brew with TAN Filtered Water

### ISSUE THREAD

**Issue by djsrv** [KnightMiner/Inspirations#15]
TAN filtered water doesn't work for making potions, stews, etc.

Currently you have to fill the cauldron with vanilla water one bottle at a time, which is a pain.

**Comment by KnightMiner** [comment]
Sorry, but this is intentional. If you can think of a good way to convert filtered water into the regular water in a cauldron, I would be open to adding the recipe (note TAN requires placing the bottle in a furnace, so it would need to be something to simulate cooking it with a bit more expense than placing over fire).

As an aside, you already have to do this for brewing stands, placing bottles in one by one, so its not that much different.

**Comment by djsrv** [comment]
Putting fire under a cauldron of filtered water yields vanilla water, perhaps?

**Comment by KnightMiner** [comment]
As I said, I want more than just placing over fire as that removes the fuel cost. Problem is its hard to think of what you would add to filtered, boiling water to purify it.

**Comment by djsrv** [comment]
Oh yeah, sorry. Skipped over that sentence.

You could probably make blaze powder craftable into 20 pinches of blaze powder, and use that to convert filtered water into vanilla water (with fire under the cauldron). Blaze powder would make sense for heating, and it wouldn't be significantly more painful over vanilla brewing since each vanilla brewing operation already requires 1/20 of a blaze powder.

And is vanilla water really necessary for making stews since the crafting recipe doesn't require water in the first place?

**Comment by KnightMiner** [comment]
I could probably switch stews to allow filtered water if I can find a clean way to special case it (right now cauldrons either request vanilla water, or any water), not sure dirty water makes sense for them though. Juices I'll leave to pure water as TAN requires that
