### ISSUE TITLE
[Compatibility] Game Crash (server) when using Mystical Grill from Project: Vibrant Journeys 

### ISSUE THREAD

**Issue by JoelZBub** [KnightMiner/Inspirations#150]
Forge Version : 14.23.5.2838
Inspirations Version : 1.12.2-0.2.8
Project: Vibrant Journeys Version : 1.12.2-1.6.4

Description of Issue:
Building a Mystical Grill from Project: Vibrant Journeys (PVJ) requires the use of a water-filled cauldron above fire. The grill is placed on top of  the cauldron, then the ingredients are placed on the grill. If Inspirations is installed, the grill operates until the placed ingredient changes to a cooked item, then the game crashes (Integrated server crash in single player, dedicated server crash in multiplayer.) 

Steps to reproduce:
1. Install PVJ and Inspirations
2. Construct and use a Mystical Grill as described here : https://github.com/mc-jt9/ProjectVibrantJourneys/wiki/Mystical-Grill#step-by-step-guide-in-images

 Crash Report link : 
https://hatebin.com/dzfjfowhum

Other notes:
This was tested with Inspirations default configuration options.
I will also report this to PVJ Issue Tracker.

**Comment by KnightMiner** [comment]
This is a bug with Mystical Grill, they are using the cauldron's metadata to determine the water level instead of the block state, which is very bad practice. I changed the metadata to also include a boiling property which causes the metadata and the level to differ.

If they just used `cauldron.getProperty(BlockCauldron.LEVEL)` like they are supposed to this crash would not happen.

**Comment by JoelZBub** [comment]
Thanks for your input. Hopefully this will lead to a resolution of the issue.

**Comment by KnightMiner** [comment]
Closing as the other author closed his side. Nothing I can do to fix it in 1.12, and sounds like he won't fix it either, which is unfortunate.

**Comment by JoelZBub** [comment]
Unfortunate indeed. Thank You
