### ISSUE TITLE
Potions fluids in buckets?

### ISSUE THREAD

**Issue by k1r0s** [KnightMiner/Inspirations#188]
related: https://github.com/KnightMiner/Inspirations/issues/106

Hi there, I have the same issue but rather I don't get buckets filled with potions liquids. It seems that buckets do not recognize potion as a (forge) liquids or maybe buckets do not work with potions.. (is there any possibility to do so?) Thanks!

**Comment by KnightMiner** [comment]
Thats because they are not, and intentionally. There is no good conversion rate between potions and a bucket of fluid, namely because if I add a potion fluid, you would expect it to work with the Immersive Enginnering one, and Immersive Engineering has decided to do 4 potion bottles per bucket. Inspirations by default does 3 potions per bucket, so thats an obvious duplication right there.

Ignoring duplication with other mods, its just not worth the effort to add an NBT fluid when you can just use potion bottles. Too many modded machines do not support NBT fluids.

**Comment by k1r0s** [comment]
> Inspirations by default does 3

I get it. Would be nice that, if enabled, big cauldrons support potion right as a forge fluid. Many players would find useful to store potions on other tanks (any fluid tank)

However I understand your take on it

**Comment by KnightMiner** [comment]
Big cauldrons in 1.12 was a huge hack. As such, don't take that as a point to design from.

1.16 makes it not a huge hack, but also makes your suggestion a lot less feasible. I basically extended the cauldron to hold 12 "levels" in a cleaner way, so most fluids interpret it as either 3 or 4 as they prefer. Plus, not planning for anymore 1.12 features.

I want to support potions as a fluid, don't get me wrong, I just don't see a good way without tying it to a unintuitive config option or opening the door to duplication bugs. The real fix requires Forge to use a number for bucket volume that is compatible with vanilla fluids, but that won't be happening anytime in the near future.

**Comment by k1r0s** [comment]
Well, again, to me I would rather let that decision to modpack owners since duplication. By configuration you can decide the bottle to bucket rate (bucket might be 1000mb). I get your point but you don't give any tools to others to overcome this issue or even decide what to do.

**Comment by KnightMiner** [comment]
This is not simply a design thing that I can leave to modpacks. The design issue is the reason I don't put in the effort to code. You are basically asking me to put in time to develop something that I do not believe is a good design so you can optionally enable it. If you want that, make an addon. With my API in either 1.12 or 1.16, it would not be hard for an addon to add this feature.
