### ISSUE TITLE
[Incompatibility] bookshelves made from Terraqueous woods have incorrect coloring

### ISSUE THREAD

**Issue by NotAVerb** [KnightMiner/Inspirations#28]
All bookshelves for Terraqueous woods are colored as though they were made from apple wood slabs.
I'm guessing this is a block ID thing on Terraqueous' end.

**Comment by KnightMiner** [comment]
Can you please provide screenshots of the wood and what you expect it to look like? It sounds as though they are dynamically tinting their woods.

**Comment by NotAVerb** [comment]
Here you go.
![2018-02-21_18 30 34](https://user-images.githubusercontent.com/30223331/36511637-599d5d0a-175f-11e8-907e-770c259cc5b9.png)

**Comment by KnightMiner** [comment]
Hmm, mind reporting the issue to Terraqueous as well? It occurs to me the issue could be from using NBT to texture their planks, which is not something I would be able to fix.

**Comment by KnightMiner** [comment]
So, apparently the author uses NBT for his slab types for the textures. Since the bookshelves depend on the slab to get the texture (since the recipe uses slabs), there is not much I can do since I cannot create a copy of his tile entity inside of mine in a clean way. Will have to go with can't fix for now.

**Comment by NotAVerb** [comment]
Would it be possible to manually override the colors of the Terraqueous derived bookshelves with a resource pack?

**Comment by KnightMiner** [comment]
It's not color it seems, it's texture. I was told on the other issue they use separate textures.

**Comment by DaedalusGame** [comment]
it's a rabbithole, but would it be possible to get plank from slab and use the plank texture instead? (this is a rabbithole because people might tweak out slab recipes)

**Comment by KnightMiner** [comment]
Getting the plank from the slab is more effort than it's worth. It means every time you craft a book shelf, it needs to do an additional reverse recipe lookup to find the plank type.

**Comment by DaedalusGame** [comment]
cached, obviously, but regardless, i agree it's a pretty bad hill to die on. Config for specific slabs to map to specific planks might work... ish, because clearly there's still the possibility of people doing nbt planks but I don't think this really warrants the change because the root problem will disappear in 1.13

**Comment by KnightMiner** [comment]
Closing as this is solved in 1.14 for most mods, and I do not intend to support NBT textures.
