### ISSUE TITLE
[Suggestion] Have full bookshelves contribute enchanting power to the enchanting table

### ISSUE THREAD

**Issue by NotAVerb** [KnightMiner/Inspirations#35]
Add the behavior of the vanilla bookshelf blocks to filled book shelves with regards to enchanting tables.

**Comment by KnightMiner** [comment]
This is something I've been meaning to do for awhile, but I just needed to come up with the proper balance. I don't want it to be too good so you are not powering an enchantment table with just one or two blocks, but not too bad to the point it is much more expensive than normal bookshelves.

I erred on the side of expensive with the following numbers:
* 1 full shelf of normal books is worth 1.5 times that of a vanilla bookshelf. This is 14 books compared to 3, but you are paying for the compactness as now you need just 10 shelves instead of 15.
* 1 full shelf of enchanted books is worth 2.5 times that of a vanilla bookshelf. This means you need just 6 shelves instead of 15.

**Comment by KnightMiner** [comment]
Added in 0.1.4
