### ISSUE TITLE
[feature request] make carpets mold to slabs as well as stairs

### ISSUE THREAD

**Issue by Zygus42** [KnightMiner/Inspirations#49]
Builds often use slabs and stairs together with full blocks - would be great to have the slabs covered by carpets as well as the adjoining stairs and full blocks,

**Comment by KnightMiner** [comment]
The reason I did not add support for slabs initally initially is twofold:

* When the carpet is lowered onto a slab, none of the carpet's model is in the original bounding box, which is awkward for targeting the carpet. I cannot lower the bounding box as they must exist in the original block.
* Adding support for slabs would leave gaps from "slab stairs", which has no easy way to fix. I could arguably add the feature and just state thats an intentional non-feature, but point one still remains.

**Comment by KnightMiner** [comment]
Looked into this again and decided against it, slabs are just too awkward with the hitbox not matching the physical location anymore
