### ISSUE TITLE
Pipes clashing with Thaumcraft.

### ISSUE THREAD

**Issue by Kurdaneva** [KnightMiner/Inspirations#84]
I currently have both the latest Thaumcraft and Inspiration, which causes an issue with Pipes. 3 iron bars create a pipe, instead of an iron plate. This is a small detail, mind you, but it's annoying to constantly have to go gamemode 1 just to grab some iron plates. I attempted to try and delete the pip file, but I'll be honest, I'm not super tech savvy. Could anyone, kindly, help with how to properly disable the pipe code? Thank you!!

**Comment by KnightMiner** [comment]
Disable pipes in the config if you must (google Forge configs), though I'd argue this issue is really on Thaumcraft's side as the generally accepted recipe is 2 iron for a plate. I'll consider changing the recipe in the future, but the easiest fix for you is either changing it yourself using a mod such as crafttweaker

**Comment by KnightMiner** [comment]
Resolved in 0.2.4
